--**********************************--
--**********************************--
sim = alife()

actor = level.object_by_id(0)

function vec3(...)
	return vector():set(...)
end

function pos(...)
	if (...) then
		local arg = {...}
		return vec3(arg[1], arg[2], arg[3]), arg[4], arg[5]
	end
	
	local pos = actor:position()
	local lv, gv = actor:level_vertex_id(), actor:game_vertex_id()
	pos.x = pos.x + 1.5 
	return pos, lv, gv
end

function con (...)
	return get_console():execute(...)
end

function spawn(...)
	return sim:create(...)
end

pstor = {
	save = function (name, val, npc)
		return alun_utils.save_var(npc or actor , name, val)
	end,
	
	load = function (name, def, npc)
		return alun_utils.load_var(npc or actor , name, def)
	end
}

function net_npc (id, tbl)
	if not tonumber(id ) then
		id = id.id
	end
	local data = sim_netp_utils.get_stalker_data(id)
	for k, v in ipairs(tbl) do
		data[k] = v
	end
	sim_netp_utils.set_stalker_data(data, id)
end

--*********************************--
--*********************************--
function net_spawn(binder)
	if not has_alife_info("mystart") then
		binder.object:give_info_portion("mystart")
		--mymodul.fstart(binder) 
	end
end

local ii, tname = 1, {'one', 'two'}
function test(aa)
	function start()
		local npc = nt.spawn('getter', vector():set(167.674072, -5.899564, 152.737625), 1253885, 184)
		npc.no_smart = true
		
		local nout = nt.spawn('zat_b40_notebook', vector():set(111.464325, -6.839030, 167.582260), 1157622, 209)
		sim:set_switch_online  (nout.id, false)
		sim:set_switch_offline (nout.id, true)
		
		sim:set_switch_online  (npc.id, false)
		sim:set_switch_offline (npc.id, true)
		
		return nout, npc
	end
	
	if aa then
		local strg, snpc = start()
		
		add_story_object(snpc.id, "chel"..tostring(tname[ii])) 
		add_story_object(strg.id, "cellnoute"..tostring(tname[ii]))
		log("~ !Start"..tostring(tname[ii]))
		
		local q = dynqst.DynQuest('mynotebook'..tostring(tname[ii]), aa, snpc, strg)
		q:setState()
		ii = ii + 1
		return q
	end 
end